#if UNITY_EDITOR

namespace Auggio
{
    internal enum ErrorCode
    {
        AUGGIO_TRACKER_NOT_UNIQUE = 1,
        AUGGIO_TRACKER_NAME_EMPTY = 2,
        AUGGIO_TRACKER_MISSING_ANCHOR = 3,
        AUGGIO_TRACKER_MISSING_ORGANIZATION_ID = 4,
        AUGGIO_TRACKER_MISSING_EXPERIENCE_ID = 5,
        AUGGIO_TRACKER_MISSING_OR_CORRUPTED_EXPERIENCE = 6,
        
        AUGGIO_PLACEHOLDER_NAME_EMPTY = 100,
        AUGGIO_PLACEHOLDER_DUPLICATE = 101,
        AUGGIO_PLACEHOLDER_NOT_REGISTERED = 102,
        AUGGIO_PLACEHOLDER_DIFFERENT_PARENT = 103
        
        
        
    }
}
#endif